### ISSUE TITLE
引用库能用mavn仓库吗？

### ISSUE THREAD

**Issue by liubailin2017** [djzhao627/fitness_Android#2]
你好，安卓的有问题。你能直接引用mavn库吗， 而不是引用本地的库。这样在我的机器上他要报错。 
如
Error:Cannot convert URL 'E:/WindowsDesktop/Life/LiLei/templates/Fitness/libs/universal-image-loader-1.8.6-with-sources.jar' to a file.

**Comment by djzhao627** [comment]
很抱歉给你造成的困扰，解决方法如下两种：

1. 请你打开 `工作目录\fitness_Android\APP\Fitness\app` 中的 `build.gradle` 文件，并删除其中的以下编译引用

```
compile files('E:/WindowsDesktop/Life/LiLei/templates/Fitness/libs/universal-image-loader-1.8.6-with-sources.jar')
compile files('E:/WindowsDesktop/Life/LiLei/templates/Fitness/libs/gson-2.6.2.jar')
compile files('E:/WindowsDesktop/Life/LiLei/templates/Fitness/libs/okhttp-3.6.0.jar')
compile files('E:/WindowsDesktop/Life/LiLei/templates/Fitness/libs/okhttputils-2_6_2.jar')
compile files('E:/WindowsDesktop/Life/LiLei/templates/Fitness/libs/okio-1.11.0.jar')
compile files('E:/WindowsDesktop/Life/LiLei/templates/Fitness/libs/android-async-http-1.4.9.jar')
```

 然后将 `工作目录\fitness_Android\APP\Fitness\libs` 中的jar包添加至引用（`右击jar包-->Add As Library..`）。


 2. 我已经更新了GitHub上的`build.gradle`文件，这里面使用了maven仓库的引用，你直接更新这个文件即可。当然别忘了删除`工作目录\fitness_Android\APP\Fitness\libs` 中未使用的本地jar包。


*最后，谢谢你提出的建议。*
