### ISSUE TITLE
Error:(1515, 5) error: style attribute '@android:attr/attr/gravity' not found.

### ISSUE THREAD

**Issue by blackist** [djzhao627/fitness_Android#3]
Android Studio 导入项目异常

`C:\Users\blackist\.gradle\caches\transforms-1\files-1.1\appcompat-v7-25.3.1.aar\23dcabac41ddc3abeb554a6295f731da\res\values\values.xml
Error:(1515, 5) error: style attribute '@android:attr/attr/gravity' not found.
Error:(1515, 5) error: style attribute 'attr/@attr/minTextSize (aka com.lilei.fitness:attr/@attr/minTextSize)' not found.`

**Comment by djzhao627** [comment]
这个没必要开个issue吧，你好好检查一下。

**Comment by 112996** [comment]
请问这个问题你有解决吗，我也遇到了同样的问题
